/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher.index'
import { Route as AuthenticatedBoardsIndexRouteImport } from './routes/_authenticated/boards.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as CheckoutSchedulePlanIdRouteImport } from './routes/checkout.schedule.$planId'
import { Route as AuthenticatedTeacherScheduleRouteImport } from './routes/_authenticated/teacher.schedule'
import { Route as AuthenticatedTeacherCalendarRouteImport } from './routes/_authenticated/teacher.calendar'
import { Route as AuthenticatedTeacherAvailabilityRouteImport } from './routes/_authenticated/teacher.availability'
import { Route as AuthenticatedOnboardingScheduleRouteImport } from './routes/_authenticated/onboarding.schedule'
import { Route as AuthenticatedOnboardingProfileRouteImport } from './routes/_authenticated/onboarding.profile'
import { Route as AuthenticatedBoardsBoardIdRouteImport } from './routes/_authenticated/boards.$boardId'
import { Route as AuthenticatedAppSubscribeRouteImport } from './routes/_authenticated/app.subscribe'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppCalendarRouteImport } from './routes/_authenticated/app.calendar'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSurveysRouteImport } from './routes/_authenticated/admin.surveys'
import { Route as AuthenticatedAdminStorageRouteImport } from './routes/_authenticated/admin.storage'
import { Route as AuthenticatedAdminSiteRouteImport } from './routes/_authenticated/admin.site'
import { Route as AuthenticatedAdminScheduleRouteImport } from './routes/_authenticated/admin.schedule'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin.resources'
import { Route as AuthenticatedAdminPayrollRouteImport } from './routes/_authenticated/admin.payroll'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminContentPromptRouteImport } from './routes/_authenticated/admin.content-prompt'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminCleanupRouteImport } from './routes/_authenticated/admin.cleanup'
import { Route as AuthenticatedAdminCartsRouteImport } from './routes/_authenticated/admin.carts'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin.calendar'
import { Route as AuthenticatedTeacherStudentsIndexRouteImport } from './routes/_authenticated/teacher.students.index'
import { Route as AuthenticatedTeacherMaterialIndexRouteImport } from './routes/_authenticated/teacher.material.index'
import { Route as AuthenticatedTeacherContentIndexRouteImport } from './routes/_authenticated/teacher.content.index'
import { Route as AuthenticatedAppLearningIndexRouteImport } from './routes/_authenticated/app.learning.index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin.users.index'
import { Route as AuthenticatedAdminPlansIndexRouteImport } from './routes/_authenticated/admin.plans.index'
import { Route as AuthenticatedTeacherStudentsStudentIdRouteImport } from './routes/_authenticated/teacher.students.$studentId'
import { Route as AuthenticatedTeacherMaterialResourceIdRouteImport } from './routes/_authenticated/teacher.material.$resourceId'
import { Route as AuthenticatedTeacherContentModuleIdRouteImport } from './routes/_authenticated/teacher.content.$moduleId'
import { Route as AuthenticatedAppLearningModuleIdRouteImport } from './routes/_authenticated/app.learning.$moduleId'
import { Route as AuthenticatedAppCheckpointCheckpointIdRouteImport } from './routes/_authenticated/app.checkpoint.$checkpointId'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin.users.$id'
import { Route as AuthenticatedBoardsBoardIdPagesPageIdRouteImport } from './routes/_authenticated/boards.$boardId.pages.$pageId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedBoardsIndexRoute =
  AuthenticatedBoardsIndexRouteImport.update({
    id: '/boards/',
    path: '/boards/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const CheckoutSchedulePlanIdRoute = CheckoutSchedulePlanIdRouteImport.update({
  id: '/checkout/schedule/$planId',
  path: '/checkout/schedule/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherScheduleRoute =
  AuthenticatedTeacherScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherCalendarRoute =
  AuthenticatedTeacherCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherAvailabilityRoute =
  AuthenticatedTeacherAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedOnboardingScheduleRoute =
  AuthenticatedOnboardingScheduleRouteImport.update({
    id: '/onboarding/schedule',
    path: '/onboarding/schedule',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingProfileRoute =
  AuthenticatedOnboardingProfileRouteImport.update({
    id: '/onboarding/profile',
    path: '/onboarding/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBoardsBoardIdRoute =
  AuthenticatedBoardsBoardIdRouteImport.update({
    id: '/boards/$boardId',
    path: '/boards/$boardId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppSubscribeRoute =
  AuthenticatedAppSubscribeRouteImport.update({
    id: '/subscribe',
    path: '/subscribe',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCalendarRoute =
  AuthenticatedAppCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSurveysRoute =
  AuthenticatedAdminSurveysRouteImport.update({
    id: '/surveys',
    path: '/surveys',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStorageRoute =
  AuthenticatedAdminStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSiteRoute = AuthenticatedAdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminScheduleRoute =
  AuthenticatedAdminScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPayrollRoute =
  AuthenticatedAdminPayrollRouteImport.update({
    id: '/payroll',
    path: '/payroll',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentPromptRoute =
  AuthenticatedAdminContentPromptRouteImport.update({
    id: '/content-prompt',
    path: '/content-prompt',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCleanupRoute =
  AuthenticatedAdminCleanupRouteImport.update({
    id: '/cleanup',
    path: '/cleanup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCartsRoute = AuthenticatedAdminCartsRouteImport.update({
  id: '/carts',
  path: '/carts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedTeacherStudentsIndexRoute =
  AuthenticatedTeacherStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherMaterialIndexRoute =
  AuthenticatedTeacherMaterialIndexRouteImport.update({
    id: '/material/',
    path: '/material/',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherContentIndexRoute =
  AuthenticatedTeacherContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedAppLearningIndexRoute =
  AuthenticatedAppLearningIndexRouteImport.update({
    id: '/learning/',
    path: '/learning/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminPlansIndexRoute =
  AuthenticatedAdminPlansIndexRouteImport.update({
    id: '/plans/',
    path: '/plans/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedTeacherStudentsStudentIdRoute =
  AuthenticatedTeacherStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherMaterialResourceIdRoute =
  AuthenticatedTeacherMaterialResourceIdRouteImport.update({
    id: '/material/$resourceId',
    path: '/material/$resourceId',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherContentModuleIdRoute =
  AuthenticatedTeacherContentModuleIdRouteImport.update({
    id: '/content/$moduleId',
    path: '/content/$moduleId',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedAppLearningModuleIdRoute =
  AuthenticatedAppLearningModuleIdRouteImport.update({
    id: '/learning/$moduleId',
    path: '/learning/$moduleId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCheckpointCheckpointIdRoute =
  AuthenticatedAppCheckpointCheckpointIdRouteImport.update({
    id: '/checkpoint/$checkpointId',
    path: '/checkpoint/$checkpointId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedBoardsBoardIdPagesPageIdRoute =
  AuthenticatedBoardsBoardIdPagesPageIdRouteImport.update({
    id: '/pages/$pageId',
    path: '/pages/$pageId',
    getParentRoute: () => AuthenticatedBoardsBoardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/carts': typeof AuthenticatedAdminCartsRoute
  '/admin/cleanup': typeof AuthenticatedAdminCleanupRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/content-prompt': typeof AuthenticatedAdminContentPromptRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/admin/surveys': typeof AuthenticatedAdminSurveysRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/subscribe': typeof AuthenticatedAppSubscribeRoute
  '/boards/$boardId': typeof AuthenticatedBoardsBoardIdRouteWithChildren
  '/onboarding/profile': typeof AuthenticatedOnboardingProfileRoute
  '/onboarding/schedule': typeof AuthenticatedOnboardingScheduleRoute
  '/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/teacher/calendar': typeof AuthenticatedTeacherCalendarRoute
  '/teacher/schedule': typeof AuthenticatedTeacherScheduleRoute
  '/checkout/schedule/$planId': typeof CheckoutSchedulePlanIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/boards/': typeof AuthenticatedBoardsIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/app/checkpoint/$checkpointId': typeof AuthenticatedAppCheckpointCheckpointIdRoute
  '/app/learning/$moduleId': typeof AuthenticatedAppLearningModuleIdRoute
  '/teacher/content/$moduleId': typeof AuthenticatedTeacherContentModuleIdRoute
  '/teacher/material/$resourceId': typeof AuthenticatedTeacherMaterialResourceIdRoute
  '/teacher/students/$studentId': typeof AuthenticatedTeacherStudentsStudentIdRoute
  '/admin/plans/': typeof AuthenticatedAdminPlansIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/app/learning/': typeof AuthenticatedAppLearningIndexRoute
  '/teacher/content/': typeof AuthenticatedTeacherContentIndexRoute
  '/teacher/material/': typeof AuthenticatedTeacherMaterialIndexRoute
  '/teacher/students/': typeof AuthenticatedTeacherStudentsIndexRoute
  '/boards/$boardId/pages/$pageId': typeof AuthenticatedBoardsBoardIdPagesPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout': typeof CheckoutIndexRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/carts': typeof AuthenticatedAdminCartsRoute
  '/admin/cleanup': typeof AuthenticatedAdminCleanupRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/content-prompt': typeof AuthenticatedAdminContentPromptRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/admin/surveys': typeof AuthenticatedAdminSurveysRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/subscribe': typeof AuthenticatedAppSubscribeRoute
  '/boards/$boardId': typeof AuthenticatedBoardsBoardIdRouteWithChildren
  '/onboarding/profile': typeof AuthenticatedOnboardingProfileRoute
  '/onboarding/schedule': typeof AuthenticatedOnboardingScheduleRoute
  '/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/teacher/calendar': typeof AuthenticatedTeacherCalendarRoute
  '/teacher/schedule': typeof AuthenticatedTeacherScheduleRoute
  '/checkout/schedule/$planId': typeof CheckoutSchedulePlanIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/boards': typeof AuthenticatedBoardsIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/app/checkpoint/$checkpointId': typeof AuthenticatedAppCheckpointCheckpointIdRoute
  '/app/learning/$moduleId': typeof AuthenticatedAppLearningModuleIdRoute
  '/teacher/content/$moduleId': typeof AuthenticatedTeacherContentModuleIdRoute
  '/teacher/material/$resourceId': typeof AuthenticatedTeacherMaterialResourceIdRoute
  '/teacher/students/$studentId': typeof AuthenticatedTeacherStudentsStudentIdRoute
  '/admin/plans': typeof AuthenticatedAdminPlansIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/app/learning': typeof AuthenticatedAppLearningIndexRoute
  '/teacher/content': typeof AuthenticatedTeacherContentIndexRoute
  '/teacher/material': typeof AuthenticatedTeacherMaterialIndexRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsIndexRoute
  '/boards/$boardId/pages/$pageId': typeof AuthenticatedBoardsBoardIdPagesPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/carts': typeof AuthenticatedAdminCartsRoute
  '/_authenticated/admin/cleanup': typeof AuthenticatedAdminCleanupRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/content-prompt': typeof AuthenticatedAdminContentPromptRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/_authenticated/admin/site': typeof AuthenticatedAdminSiteRoute
  '/_authenticated/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/_authenticated/admin/surveys': typeof AuthenticatedAdminSurveysRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/subscribe': typeof AuthenticatedAppSubscribeRoute
  '/_authenticated/boards/$boardId': typeof AuthenticatedBoardsBoardIdRouteWithChildren
  '/_authenticated/onboarding/profile': typeof AuthenticatedOnboardingProfileRoute
  '/_authenticated/onboarding/schedule': typeof AuthenticatedOnboardingScheduleRoute
  '/_authenticated/teacher/availability': typeof AuthenticatedTeacherAvailabilityRoute
  '/_authenticated/teacher/calendar': typeof AuthenticatedTeacherCalendarRoute
  '/_authenticated/teacher/schedule': typeof AuthenticatedTeacherScheduleRoute
  '/checkout/schedule/$planId': typeof CheckoutSchedulePlanIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/boards/': typeof AuthenticatedBoardsIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/app/checkpoint/$checkpointId': typeof AuthenticatedAppCheckpointCheckpointIdRoute
  '/_authenticated/app/learning/$moduleId': typeof AuthenticatedAppLearningModuleIdRoute
  '/_authenticated/teacher/content/$moduleId': typeof AuthenticatedTeacherContentModuleIdRoute
  '/_authenticated/teacher/material/$resourceId': typeof AuthenticatedTeacherMaterialResourceIdRoute
  '/_authenticated/teacher/students/$studentId': typeof AuthenticatedTeacherStudentsStudentIdRoute
  '/_authenticated/admin/plans/': typeof AuthenticatedAdminPlansIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/app/learning/': typeof AuthenticatedAppLearningIndexRoute
  '/_authenticated/teacher/content/': typeof AuthenticatedTeacherContentIndexRoute
  '/_authenticated/teacher/material/': typeof AuthenticatedTeacherMaterialIndexRoute
  '/_authenticated/teacher/students/': typeof AuthenticatedTeacherStudentsIndexRoute
  '/_authenticated/boards/$boardId/pages/$pageId': typeof AuthenticatedBoardsBoardIdPagesPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/admin'
    | '/app'
    | '/notifications'
    | '/teacher'
    | '/auth/callback'
    | '/checkout/$planId'
    | '/checkout/return'
    | '/checkout/'
    | '/admin/calendar'
    | '/admin/carts'
    | '/admin/cleanup'
    | '/admin/content'
    | '/admin/content-prompt'
    | '/admin/notifications'
    | '/admin/payroll'
    | '/admin/resources'
    | '/admin/schedule'
    | '/admin/site'
    | '/admin/storage'
    | '/admin/surveys'
    | '/admin/users'
    | '/app/calendar'
    | '/app/settings'
    | '/app/subscribe'
    | '/boards/$boardId'
    | '/onboarding/profile'
    | '/onboarding/schedule'
    | '/teacher/availability'
    | '/teacher/calendar'
    | '/teacher/schedule'
    | '/checkout/schedule/$planId'
    | '/admin/'
    | '/app/'
    | '/boards/'
    | '/teacher/'
    | '/admin/users/$id'
    | '/app/checkpoint/$checkpointId'
    | '/app/learning/$moduleId'
    | '/teacher/content/$moduleId'
    | '/teacher/material/$resourceId'
    | '/teacher/students/$studentId'
    | '/admin/plans/'
    | '/admin/users/'
    | '/app/learning/'
    | '/teacher/content/'
    | '/teacher/material/'
    | '/teacher/students/'
    | '/boards/$boardId/pages/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/notifications'
    | '/auth/callback'
    | '/checkout/$planId'
    | '/checkout/return'
    | '/checkout'
    | '/admin/calendar'
    | '/admin/carts'
    | '/admin/cleanup'
    | '/admin/content'
    | '/admin/content-prompt'
    | '/admin/notifications'
    | '/admin/payroll'
    | '/admin/resources'
    | '/admin/schedule'
    | '/admin/site'
    | '/admin/storage'
    | '/admin/surveys'
    | '/app/calendar'
    | '/app/settings'
    | '/app/subscribe'
    | '/boards/$boardId'
    | '/onboarding/profile'
    | '/onboarding/schedule'
    | '/teacher/availability'
    | '/teacher/calendar'
    | '/teacher/schedule'
    | '/checkout/schedule/$planId'
    | '/admin'
    | '/app'
    | '/boards'
    | '/teacher'
    | '/admin/users/$id'
    | '/app/checkpoint/$checkpointId'
    | '/app/learning/$moduleId'
    | '/teacher/content/$moduleId'
    | '/teacher/material/$resourceId'
    | '/teacher/students/$studentId'
    | '/admin/plans'
    | '/admin/users'
    | '/app/learning'
    | '/teacher/content'
    | '/teacher/material'
    | '/teacher/students'
    | '/boards/$boardId/pages/$pageId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/notifications'
    | '/_authenticated/teacher'
    | '/auth/callback'
    | '/checkout/$planId'
    | '/checkout/return'
    | '/checkout/'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/carts'
    | '/_authenticated/admin/cleanup'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/content-prompt'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/payroll'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/schedule'
    | '/_authenticated/admin/site'
    | '/_authenticated/admin/storage'
    | '/_authenticated/admin/surveys'
    | '/_authenticated/admin/users'
    | '/_authenticated/app/calendar'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/subscribe'
    | '/_authenticated/boards/$boardId'
    | '/_authenticated/onboarding/profile'
    | '/_authenticated/onboarding/schedule'
    | '/_authenticated/teacher/availability'
    | '/_authenticated/teacher/calendar'
    | '/_authenticated/teacher/schedule'
    | '/checkout/schedule/$planId'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/boards/'
    | '/_authenticated/teacher/'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/app/checkpoint/$checkpointId'
    | '/_authenticated/app/learning/$moduleId'
    | '/_authenticated/teacher/content/$moduleId'
    | '/_authenticated/teacher/material/$resourceId'
    | '/_authenticated/teacher/students/$studentId'
    | '/_authenticated/admin/plans/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/app/learning/'
    | '/_authenticated/teacher/content/'
    | '/_authenticated/teacher/material/'
    | '/_authenticated/teacher/students/'
    | '/_authenticated/boards/$boardId/pages/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CheckoutSchedulePlanIdRoute: typeof CheckoutSchedulePlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/boards/': {
      id: '/_authenticated/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof AuthenticatedBoardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/checkout/schedule/$planId': {
      id: '/checkout/schedule/$planId'
      path: '/checkout/schedule/$planId'
      fullPath: '/checkout/schedule/$planId'
      preLoaderRoute: typeof CheckoutSchedulePlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher/schedule': {
      id: '/_authenticated/teacher/schedule'
      path: '/schedule'
      fullPath: '/teacher/schedule'
      preLoaderRoute: typeof AuthenticatedTeacherScheduleRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/calendar': {
      id: '/_authenticated/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof AuthenticatedTeacherCalendarRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/availability': {
      id: '/_authenticated/teacher/availability'
      path: '/availability'
      fullPath: '/teacher/availability'
      preLoaderRoute: typeof AuthenticatedTeacherAvailabilityRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/onboarding/schedule': {
      id: '/_authenticated/onboarding/schedule'
      path: '/onboarding/schedule'
      fullPath: '/onboarding/schedule'
      preLoaderRoute: typeof AuthenticatedOnboardingScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/profile': {
      id: '/_authenticated/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof AuthenticatedOnboardingProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/boards/$boardId': {
      id: '/_authenticated/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof AuthenticatedBoardsBoardIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/subscribe': {
      id: '/_authenticated/app/subscribe'
      path: '/subscribe'
      fullPath: '/app/subscribe'
      preLoaderRoute: typeof AuthenticatedAppSubscribeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/calendar': {
      id: '/_authenticated/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AuthenticatedAppCalendarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/surveys': {
      id: '/_authenticated/admin/surveys'
      path: '/surveys'
      fullPath: '/admin/surveys'
      preLoaderRoute: typeof AuthenticatedAdminSurveysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/storage': {
      id: '/_authenticated/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AuthenticatedAdminStorageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/site': {
      id: '/_authenticated/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AuthenticatedAdminSiteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/schedule': {
      id: '/_authenticated/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AuthenticatedAdminScheduleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payroll': {
      id: '/_authenticated/admin/payroll'
      path: '/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AuthenticatedAdminPayrollRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content-prompt': {
      id: '/_authenticated/admin/content-prompt'
      path: '/content-prompt'
      fullPath: '/admin/content-prompt'
      preLoaderRoute: typeof AuthenticatedAdminContentPromptRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cleanup': {
      id: '/_authenticated/admin/cleanup'
      path: '/cleanup'
      fullPath: '/admin/cleanup'
      preLoaderRoute: typeof AuthenticatedAdminCleanupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/carts': {
      id: '/_authenticated/admin/carts'
      path: '/carts'
      fullPath: '/admin/carts'
      preLoaderRoute: typeof AuthenticatedAdminCartsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/teacher/students/': {
      id: '/_authenticated/teacher/students/'
      path: '/students'
      fullPath: '/teacher/students/'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/material/': {
      id: '/_authenticated/teacher/material/'
      path: '/material'
      fullPath: '/teacher/material/'
      preLoaderRoute: typeof AuthenticatedTeacherMaterialIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/content/': {
      id: '/_authenticated/teacher/content/'
      path: '/content'
      fullPath: '/teacher/content/'
      preLoaderRoute: typeof AuthenticatedTeacherContentIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/app/learning/': {
      id: '/_authenticated/app/learning/'
      path: '/learning'
      fullPath: '/app/learning/'
      preLoaderRoute: typeof AuthenticatedAppLearningIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/plans/': {
      id: '/_authenticated/admin/plans/'
      path: '/plans'
      fullPath: '/admin/plans/'
      preLoaderRoute: typeof AuthenticatedAdminPlansIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/teacher/students/$studentId': {
      id: '/_authenticated/teacher/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/teacher/students/$studentId'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/material/$resourceId': {
      id: '/_authenticated/teacher/material/$resourceId'
      path: '/material/$resourceId'
      fullPath: '/teacher/material/$resourceId'
      preLoaderRoute: typeof AuthenticatedTeacherMaterialResourceIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/content/$moduleId': {
      id: '/_authenticated/teacher/content/$moduleId'
      path: '/content/$moduleId'
      fullPath: '/teacher/content/$moduleId'
      preLoaderRoute: typeof AuthenticatedTeacherContentModuleIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/app/learning/$moduleId': {
      id: '/_authenticated/app/learning/$moduleId'
      path: '/learning/$moduleId'
      fullPath: '/app/learning/$moduleId'
      preLoaderRoute: typeof AuthenticatedAppLearningModuleIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/checkpoint/$checkpointId': {
      id: '/_authenticated/app/checkpoint/$checkpointId'
      path: '/checkpoint/$checkpointId'
      fullPath: '/app/checkpoint/$checkpointId'
      preLoaderRoute: typeof AuthenticatedAppCheckpointCheckpointIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/boards/$boardId/pages/$pageId': {
      id: '/_authenticated/boards/$boardId/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/boards/$boardId/pages/$pageId'
      preLoaderRoute: typeof AuthenticatedBoardsBoardIdPagesPageIdRouteImport
      parentRoute: typeof AuthenticatedBoardsBoardIdRoute
    }
  }
}

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminCartsRoute: typeof AuthenticatedAdminCartsRoute
  AuthenticatedAdminCleanupRoute: typeof AuthenticatedAdminCleanupRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminContentPromptRoute: typeof AuthenticatedAdminContentPromptRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPayrollRoute: typeof AuthenticatedAdminPayrollRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminScheduleRoute: typeof AuthenticatedAdminScheduleRoute
  AuthenticatedAdminSiteRoute: typeof AuthenticatedAdminSiteRoute
  AuthenticatedAdminStorageRoute: typeof AuthenticatedAdminStorageRoute
  AuthenticatedAdminSurveysRoute: typeof AuthenticatedAdminSurveysRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPlansIndexRoute: typeof AuthenticatedAdminPlansIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
  AuthenticatedAdminCartsRoute: AuthenticatedAdminCartsRoute,
  AuthenticatedAdminCleanupRoute: AuthenticatedAdminCleanupRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminContentPromptRoute: AuthenticatedAdminContentPromptRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPayrollRoute: AuthenticatedAdminPayrollRoute,
  AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
  AuthenticatedAdminScheduleRoute: AuthenticatedAdminScheduleRoute,
  AuthenticatedAdminSiteRoute: AuthenticatedAdminSiteRoute,
  AuthenticatedAdminStorageRoute: AuthenticatedAdminStorageRoute,
  AuthenticatedAdminSurveysRoute: AuthenticatedAdminSurveysRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPlansIndexRoute: AuthenticatedAdminPlansIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCalendarRoute: typeof AuthenticatedAppCalendarRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSubscribeRoute: typeof AuthenticatedAppSubscribeRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCheckpointCheckpointIdRoute: typeof AuthenticatedAppCheckpointCheckpointIdRoute
  AuthenticatedAppLearningModuleIdRoute: typeof AuthenticatedAppLearningModuleIdRoute
  AuthenticatedAppLearningIndexRoute: typeof AuthenticatedAppLearningIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCalendarRoute: AuthenticatedAppCalendarRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSubscribeRoute: AuthenticatedAppSubscribeRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCheckpointCheckpointIdRoute:
    AuthenticatedAppCheckpointCheckpointIdRoute,
  AuthenticatedAppLearningModuleIdRoute: AuthenticatedAppLearningModuleIdRoute,
  AuthenticatedAppLearningIndexRoute: AuthenticatedAppLearningIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedTeacherRouteChildren {
  AuthenticatedTeacherAvailabilityRoute: typeof AuthenticatedTeacherAvailabilityRoute
  AuthenticatedTeacherCalendarRoute: typeof AuthenticatedTeacherCalendarRoute
  AuthenticatedTeacherScheduleRoute: typeof AuthenticatedTeacherScheduleRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedTeacherContentModuleIdRoute: typeof AuthenticatedTeacherContentModuleIdRoute
  AuthenticatedTeacherMaterialResourceIdRoute: typeof AuthenticatedTeacherMaterialResourceIdRoute
  AuthenticatedTeacherStudentsStudentIdRoute: typeof AuthenticatedTeacherStudentsStudentIdRoute
  AuthenticatedTeacherContentIndexRoute: typeof AuthenticatedTeacherContentIndexRoute
  AuthenticatedTeacherMaterialIndexRoute: typeof AuthenticatedTeacherMaterialIndexRoute
  AuthenticatedTeacherStudentsIndexRoute: typeof AuthenticatedTeacherStudentsIndexRoute
}

const AuthenticatedTeacherRouteChildren: AuthenticatedTeacherRouteChildren = {
  AuthenticatedTeacherAvailabilityRoute: AuthenticatedTeacherAvailabilityRoute,
  AuthenticatedTeacherCalendarRoute: AuthenticatedTeacherCalendarRoute,
  AuthenticatedTeacherScheduleRoute: AuthenticatedTeacherScheduleRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  AuthenticatedTeacherContentModuleIdRoute:
    AuthenticatedTeacherContentModuleIdRoute,
  AuthenticatedTeacherMaterialResourceIdRoute:
    AuthenticatedTeacherMaterialResourceIdRoute,
  AuthenticatedTeacherStudentsStudentIdRoute:
    AuthenticatedTeacherStudentsStudentIdRoute,
  AuthenticatedTeacherContentIndexRoute: AuthenticatedTeacherContentIndexRoute,
  AuthenticatedTeacherMaterialIndexRoute:
    AuthenticatedTeacherMaterialIndexRoute,
  AuthenticatedTeacherStudentsIndexRoute:
    AuthenticatedTeacherStudentsIndexRoute,
}

const AuthenticatedTeacherRouteWithChildren =
  AuthenticatedTeacherRoute._addFileChildren(AuthenticatedTeacherRouteChildren)

interface AuthenticatedBoardsBoardIdRouteChildren {
  AuthenticatedBoardsBoardIdPagesPageIdRoute: typeof AuthenticatedBoardsBoardIdPagesPageIdRoute
}

const AuthenticatedBoardsBoardIdRouteChildren: AuthenticatedBoardsBoardIdRouteChildren =
  {
    AuthenticatedBoardsBoardIdPagesPageIdRoute:
      AuthenticatedBoardsBoardIdPagesPageIdRoute,
  }

const AuthenticatedBoardsBoardIdRouteWithChildren =
  AuthenticatedBoardsBoardIdRoute._addFileChildren(
    AuthenticatedBoardsBoardIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRouteWithChildren
  AuthenticatedBoardsBoardIdRoute: typeof AuthenticatedBoardsBoardIdRouteWithChildren
  AuthenticatedOnboardingProfileRoute: typeof AuthenticatedOnboardingProfileRoute
  AuthenticatedOnboardingScheduleRoute: typeof AuthenticatedOnboardingScheduleRoute
  AuthenticatedBoardsIndexRoute: typeof AuthenticatedBoardsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRouteWithChildren,
  AuthenticatedBoardsBoardIdRoute: AuthenticatedBoardsBoardIdRouteWithChildren,
  AuthenticatedOnboardingProfileRoute: AuthenticatedOnboardingProfileRoute,
  AuthenticatedOnboardingScheduleRoute: AuthenticatedOnboardingScheduleRoute,
  AuthenticatedBoardsIndexRoute: AuthenticatedBoardsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CheckoutSchedulePlanIdRoute: CheckoutSchedulePlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
